# Generated by Django 3.2.4 on 2021-06-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='seller_name',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=8)),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_category')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
        ),
    ]
