# Generated by Django 4.0.5 on 2022-07-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login_sys', '0003_alter_customer_f_name_alter_customer_l_name_and_more'),
        ('main', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('price', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('shipping_address', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_login_sys.customer')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.products')),
            ],
        ),
    ]
