# Generated by Django 4.0.5 on 2022-07-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
