# Generated by Django 3.2.4 on 2021-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=50, unique=True),
        ),
    ]
