# Generated by Django 4.0.5 on 2022-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login_sys', '0002_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='f_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=254, unique=True), max_length=500, unique=True),
        ),
    ]
